version: "3.8"

services:
  ebbflowmanager:
    # image: ghcr.io/phofmeier/ebbflowmanager:latest
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./manager/config/config.yml:/home/app/config.yml
      - ./manager/logs:/home/app/logs
    depends_on:
      - db
      - mosquitto
    ports:
      - 5006:5006

  mqtt2db:
    image: ghcr.io/phofmeier/mqtt2db:latest
    restart: unless-stopped
    # Custom Configuration
    volumes:
      - ./mqtt2db/config/config.yml:/home/app/config.yml
      - ./mqtt2db/logs:/home/app/logs

    depends_on:
      - db
      - mosquitto

  # Database
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

    ports:
      - 27017:27017

  # MQTT brocker
  mosquitto:
    image: eclipse-mosquitto:latest
    #hostname: mosquitto
    #container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      # - "9001:9001"

    # Add for custom configuration
    #  volumes:
    #    - ./mosquitto:/etc/mosquitto
    #    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  mongodb-data:
