database:
  collection_config_name: config_static
  collection_status_name: status_static
  connection_string: db:27017
  database_name: efc
  id_field_name: id
logging:
  disable_existing_loggers: false
  formatters:
    f:
      format: "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
  handlers:
    h:
      class: logging.StreamHandler
      formatter: f
      level: 20
  root:
    handlers:
      - h
    level: 20
  version: 1
mqtt:
  broker: localhost
  new_config_publish_topic: ef/efc/config/set
  port: 1883
