database:
  connection_string: db:27017
  static:
    add_received_timestamp: true
    id_field_name: id
    received_timestamp_name: ts_received
  timed:
    meta_field_name: metadata
    time_field_name: timestamp
logging:
  disable_existing_loggers: false
  formatters:
    f:
      format: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
  handlers:
    h:
      class: logging.StreamHandler
      formatter: f
      level: 10
  root:
    handlers:
    - h
    level: 10
  version: 1
mqtt:
  broker: mosquitto
  channel_prefix: ef
  port: 1883
